CREATE TABLE [dbo].[tbl_Blog_FAQ]
(
[Blog_FAQ_Id] INT IDENTITY (1,1) NOT NULL,
[Blog_FAQ_Code] NVARCHAR (50) NOT NULL UNIQUE,
[FK_Blog_Id] INT NULL,
[Blog_FAQ_Question] NVARCHAR(MAX) NULL,
[Blog_FAQ_Answer] NVARCHAR(MAX) NULL,


[Created_On] DATETIME NOT NULL DEFAULT(GETDATE()),
[Created_By] INT NOT NULL,
[Created_IP] NVARCHAR(MAX) NULL,
[Modified_On] DATETIME NULL DEFAULT(NULL),
[Modified_By] INT NULL DEFAULT(NULL),
[Modified_IP] NVARCHAR(MAX) NULL,
[Is_Active] BIT NOT NULL DEFAULT(1)

CONSTRAINT[PK_tbl_Blog_FAQ] PRIMARY KEY CLUSTERED ([Blog_FAQ_Id] ASC) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
 