CREATE TABLE [dbo].[tbl_Product_Image]
(
[Product_Image_Id] INT IDENTITY (1,1) NOT NULL,
[Product_Image_Code] NVARCHAR (MAX) NULL,
[FK_Product_Id] INT NULL,
[Product_Details_Image]  NVARCHAR(MAX) NULL,
[Product_Details_Decriptions]  NVARCHAR(MAX) NULL,

[Created_On] DATETIME NOT NULL DEFAULT(GETDATE()),
[Created_By] INT NOT NULL,
[Created_IP] NVARCHAR(MAX) NULL,
[Modified_On] DATETIME NULL DEFAULT(NULL),
[Modified_By] INT NULL DEFAULT(NULL),
[Modified_IP] NVARCHAR(MAX) NULL,
[Is_Active] BIT NOT NULL DEFAULT(1)

CONSTRAINT[PK_tbl_Product_Image] PRIMARY KEY CLUSTERED ([Product_Image_Id] ASC) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
 